//const { test, expect } = require('@playwright/test');
import { test, expect } from '@playwright/test';

test.use({
  headless: true, 
  ignoreHTTPSErrors: true 
});
  
  test('flujo completo de calificación', async ({ page }) => {

    await page.goto('https://172.24.80.51/netscore/#/auth/login');
    await page.getByRole('textbox', { name: 'Ingrese su usuario' }).click();
    await page.getByRole('textbox', { name: 'Ingrese su usuario' }).fill('wmdelgado');
    await page.getByRole('textbox', { name: 'Ingrese su contraseña' }).click();
    await page.getByRole('textbox', { name: 'Ingrese su contraseña' }).fill('Temporal20*');
    await page.getByRole('button', { name: 'Iniciar sesión' }).click();
    await page.getByRole('link', { name: ' Calificaciones' }).click();
    await page.getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'NETLIFE - CSI' }).click();
    await page.locator('p-dropdown').filter({ hasText: 'Buscar agente' }).getByLabel('dropdown trigger').click();
    await page.getByRole('option', { name: 'Vanegas Gomez Laura' }).locator('div').first().click();
    await page.locator('app-main-header button').click();
    await await page.getByText('Sep', { exact: true }).click();
    await page.locator('app-form-header p-calendar').getByRole('button').click();
    await page.locator('(//span[@draggable=\'false\'])[25]').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').fill('gdfghg');
    await page.getByTitle('undefined').getByLabel('dropdown trigger').click();
    await page.getByRole('option', { name: 'Activar correo electronico' }).click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').fill('35465346');
    await page.locator('#solucion').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Excelente' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).fill('sdgdgf');
    await page.getByRole('button', { name: ' Guardar' }).click();
    await page.getByRole('button', { name: 'Sí' }).click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').fill('dggdg');
    await page.locator('app-form-header p-calendar').getByRole('button').click();
    await page.getByText('21', { exact: true }).click();
    await page.getByTitle('undefined').getByLabel('dropdown trigger').click();
    await page.getByRole('option', { name: 'Informacion de planes y' }).click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').fill('53535');
    await page.locator('#solucion').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Excelente' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).fill('gsgdg');
    await page.getByRole('button', { name: ' Guardar' }).click();
    await page.getByRole('button', { name: 'Sí' }).click();
    await page.locator('app-form-header p-calendar').getByRole('button').click();
    await page.getByText('21', { exact: true }).click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').fill('gdfhdfh');
    await page.getByTitle('undefined').getByLabel('dropdown trigger').click();
    await page.getByRole('option', { name: 'Reactivación de servicio' }).locator('div').first().click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').fill('2425');
    await page.locator('#solucion').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Excelente' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).fill('ggdrgd');
    await page.getByRole('button', { name: ' Guardar' }).click();
    await page.getByRole('button', { name: 'Sí' }).click();
    await page.locator('app-form-header p-calendar').getByRole('button').click();
    await page.getByText('21', { exact: true }).click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').fill('gdfghdg');
    await page.getByTitle('undefined').getByLabel('dropdown trigger').click();
    await page.getByText('Actualizar Datos', { exact: true }).click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').fill('3543634');
    await page.locator('#solucion').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Excelente' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).fill('dgdg');
    await page.getByRole('button', { name: ' Guardar' }).click();
    await page.getByRole('button', { name: 'Sí' }).click();
    await page.locator('app-form-header p-calendar').getByRole('button').click();
    await page.getByText('21', { exact: true }).click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(7) > .flex > .p-inputtext').fill('dggdfd');
    await page.getByTitle('undefined').getByLabel('dropdown trigger').click();
    await page.getByText('Retencion de cliente').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').click();
    await page.locator('div:nth-child(9) > .flex > .p-inputtext').fill('243252345');
    await page.locator('#solucion').getByRole('button', { name: 'dropdown trigger' }).click();
    await page.getByRole('option', { name: 'Excelente' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).click();
    await page.getByRole('textbox', { name: 'Escribe un comentario' }).fill('gdhgdrh');
    await page.getByRole('button', { name: ' Guardar' }).click();
    await page.getByRole('button', { name: 'Sí' }).click();
    const botonGuardarFinal = page.getByRole('button', { name: ' Guardar' });
  });